//! Storage trait for list allocators.
//!
//! This module provides the trait that abstracts over different storage backends
//! for the List type. The `create_list!` macro generates implementations of this
//! trait that connect to TLS-based slab allocators.

use nexus_slab::Key;

use crate::list::Node;

/// Storage operations required by List.
///
/// This trait is implemented by marker types generated by `create_list!`.
/// It provides the connection between list operations and the TLS slab.
///
/// # Safety
///
/// Implementations must ensure:
/// - Keys are valid for the lifetime of the data
/// - `get_unchecked` / `get_unchecked_mut` are only called with valid keys
/// - `remove_unchecked` is only called once per key
pub trait ListStorage<T: 'static>: Copy {
    /// Returns `true` if the key points to a valid, occupied slot.
    fn contains_key(key: Key) -> bool;

    /// Returns a reference to the node at `key`.
    ///
    /// Returns `None` if the key is invalid or the slot is vacant.
    ///
    /// # Safety
    ///
    /// Caller must ensure no mutable references to this node exist.
    unsafe fn get(key: Key) -> Option<&'static Node<T>>;

    /// Returns a mutable reference to the node at `key`.
    ///
    /// Returns `None` if the key is invalid or the slot is vacant.
    ///
    /// # Safety
    ///
    /// Caller must ensure no other references to this node exist.
    #[allow(clippy::mut_from_ref)]
    unsafe fn get_mut(key: Key) -> Option<&'static mut Node<T>>;

    /// Returns a reference without validity checks.
    ///
    /// # Safety
    ///
    /// Key must be valid and occupied. No mutable references may exist.
    unsafe fn get_unchecked(key: Key) -> &'static Node<T>;

    /// Returns a mutable reference without validity checks.
    ///
    /// # Safety
    ///
    /// Key must be valid and occupied. No other references may exist.
    #[allow(clippy::mut_from_ref)]
    unsafe fn get_unchecked_mut(key: Key) -> &'static mut Node<T>;

    /// Tries to remove the node at `key`, returning it if present.
    ///
    /// Returns `None` if the key is invalid or the slot is vacant.
    fn try_remove(key: Key) -> Option<Node<T>>;

    /// Removes the node at `key` without validity checks.
    ///
    /// # Safety
    ///
    /// Key must be valid and occupied.
    unsafe fn remove_unchecked(key: Key) -> Node<T>;
}
