//! Generic slab allocator trait and slot type.
//!
//! This module provides:
//! - [`Alloc`] - trait for ZST allocators generated by macros
//! - [`Slot`] - 8-byte RAII handle generic over allocator
//! - [`BoundedAlloc`] / [`UnboundedAlloc`] - marker traits

use std::fmt;
use std::marker::PhantomData;
use std::mem::ManuallyDrop;
use std::ops::{Deref, DerefMut};
use std::ptr;

use crate::shared::RcInner;

use crate::Key;
use crate::shared::SlotCell;

// =============================================================================
// Full<T>
// =============================================================================

/// Error returned when a bounded allocator is full.
///
/// Contains the value that could not be allocated, allowing recovery.
pub struct Full<T>(pub T);

impl<T> Full<T> {
    /// Consumes the error, returning the value that could not be allocated.
    #[inline]
    pub fn into_inner(self) -> T {
        self.0
    }
}

impl<T> fmt::Debug for Full<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("Full(..)")
    }
}

impl<T> fmt::Display for Full<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("allocator full")
    }
}

// =============================================================================
// Traits
// =============================================================================

/// Trait for zero-sized slab allocators backed by thread-local storage.
///
/// Each macro-generated allocator is a ZST that implements this trait.
/// All operations go through associated functions (no `&self`) since
/// the backing storage lives in a `thread_local!`.
///
/// # Safety
///
/// Implementors must guarantee:
/// - `try_alloc` returns a valid, claimed slot pointer with value written
/// - `dealloc` correctly returns the slot to the freelist (by key)
/// - `dealloc_ptr` correctly returns the slot to the freelist (by pointer)
/// - `slot_cell` returns a valid pointer for any key returned by `try_alloc`
/// - All operations are single-threaded (TLS-backed)
pub unsafe trait Alloc: Sized + 'static {
    /// The type stored in each slot.
    type Item: 'static;

    /// Claim a slot, write the value, and mark it occupied.
    ///
    /// Returns `Err(Full(value))` if the allocator is full, giving the
    /// value back to the caller.
    fn try_alloc(value: Self::Item) -> Result<*mut SlotCell<Self::Item>, Full<Self::Item>>;

    /// Claim a slot, write the value, and mark it occupied.
    ///
    /// # Panics
    ///
    /// Panics with "out of memory" if the allocator is full.
    #[inline]
    fn alloc(value: Self::Item) -> *mut SlotCell<Self::Item> {
        Self::try_alloc(value).expect("out of memory")
    }

    /// Return a slot to the freelist by key (cold path).
    ///
    /// # Safety
    ///
    /// - `key` must refer to a previously allocated, occupied slot
    /// - The value must already be dropped or moved out
    unsafe fn dealloc(key: Key);

    /// Return a slot to the freelist by pointer (hot path).
    ///
    /// This avoids the key→pointer round-trip that `dealloc` requires.
    ///
    /// # Safety
    ///
    /// - `slot_ptr` must point to a previously allocated, occupied slot
    /// - The value must already be dropped or moved out
    unsafe fn dealloc_ptr(slot_ptr: *mut SlotCell<Self::Item>);

    /// Get the slot cell pointer for a key.
    ///
    /// # Safety
    ///
    /// `key` must refer to a valid slot within the slab.
    unsafe fn slot_cell(key: Key) -> *mut SlotCell<Self::Item>;

    /// Compute the key for a slot pointer (cold path).
    ///
    /// This is the inverse of `slot_cell`: given a pointer, compute the key.
    /// Used for lazy key computation in `Slot::key()`.
    fn slot_index(slot_ptr: *mut SlotCell<Self::Item>) -> Key;
}

/// Marker trait for bounded (fixed-capacity) allocators.
pub trait BoundedAlloc: Alloc {}

/// Marker trait for unbounded (growable) allocators.
pub trait UnboundedAlloc: Alloc {}

// =============================================================================
// Slot<A>
// =============================================================================

/// RAII handle to a slab-allocated value, generic over allocator.
///
/// `Slot<A>` is 8 bytes (one pointer). The key is computed lazily from the
/// pointer when needed.
///
/// This is the slot type generated by `bounded_allocator!` and
/// `unbounded_allocator!` macros via `type Slot = alloc::Slot<Allocator>`.
///
/// # `Borrow` / HashMap Keys
///
/// `Slot` does **not** implement [`Borrow<T>`](std::borrow::Borrow). A generic
/// impl conflicts with `core`'s blanket `impl<T> Borrow<T> for T`, and
/// macro-generated impls break under the orphan rule when the allocated type
/// is defined in a different crate from the allocator. As a result, `Slot`
/// cannot be used directly as a `HashMap` key that borrows `T`. Use
/// [`Slot::key()`] for map keys instead.
///
/// # Thread Safety
///
/// `Slot` is `!Send` and `!Sync` (via `PhantomData<*const ()>` inside the
/// marker). It must only be used from the thread that created it.
#[must_use = "dropping Slot returns it to the allocator"]
pub struct Slot<A: Alloc> {
    slot_ptr: *mut SlotCell<A::Item>,
    // PhantomData carries the allocator type AND makes Slot !Send + !Sync
    // (*mut is !Send + !Sync, and PhantomData<A> ties the type)
    _marker: PhantomData<(A, *const ())>,
}

impl<A: Alloc> Slot<A> {
    /// Creates a new slot containing the given value.
    ///
    /// # Panics
    ///
    /// Panics with "out of memory" if the allocator is full (bounded only).
    #[inline]
    pub fn new(value: A::Item) -> Self {
        Slot {
            slot_ptr: A::alloc(value),
            _marker: PhantomData,
        }
    }

    /// Tries to create a new slot containing the given value.
    ///
    /// Returns `Err(Full(value))` if the allocator is at capacity,
    /// giving the value back to the caller.
    #[inline]
    pub fn try_new(value: A::Item) -> Result<Self, Full<A::Item>> {
        let slot_ptr = A::try_alloc(value)?;
        Ok(Slot {
            slot_ptr,
            _marker: PhantomData,
        })
    }

    /// Returns the key for this slot.
    ///
    /// Lazily computed from pointer offset. This is a cold-path operation.
    #[inline]
    pub fn key(&self) -> Key {
        A::slot_index(self.slot_ptr)
    }

    /// Leaks the slot, returning its key for later access.
    ///
    /// The slot is NOT deallocated. Use key-based methods to access
    /// or eventually remove it.
    #[inline]
    pub fn leak(self) -> Key {
        let key = self.key();
        std::mem::forget(self);
        key
    }

    /// Extracts the value from the slot, deallocating the slot.
    ///
    /// This is analogous to `Box::into_inner`.
    pub fn into_inner(self) -> A::Item {
        // SAFETY: We own the slot, union field `value` is active
        let value = unsafe { ptr::read((*self.slot_ptr).value.as_ptr()) };

        // SAFETY: Value has been moved out, slot_ptr is valid
        unsafe { A::dealloc_ptr(self.slot_ptr) };

        std::mem::forget(self);
        value
    }

    /// Replaces the value in the slot, returning the old value.
    #[inline]
    pub fn replace(&mut self, value: A::Item) -> A::Item {
        // SAFETY: We own the slot exclusively (&mut self), union field `value` is active
        unsafe {
            let val_ptr = (*(*self.slot_ptr).value).as_mut_ptr();
            let old = ptr::read(val_ptr);
            ptr::write(val_ptr, value);
            old
        }
    }

    /// Returns a reference to the value for the given key.
    ///
    /// # Safety
    ///
    /// The key must be valid (from `leak()` or `key()`, not yet removed).
    #[inline]
    pub unsafe fn from_key(key: Key) -> &'static A::Item {
        // SAFETY: Caller guarantees key validity. TLS storage is 'static.
        // Union field `value` is active because the slot is occupied.
        let cell = unsafe { A::slot_cell(key) };
        unsafe { (*cell).value.assume_init_ref() }
    }

    /// Returns a mutable reference to the value for the given key.
    ///
    /// # Safety
    ///
    /// The key must be valid and no other references to this slot exist.
    #[inline]
    pub unsafe fn from_key_mut(key: Key) -> &'static mut A::Item {
        // SAFETY: Caller guarantees key validity and exclusivity.
        // Union field `value` is active because the slot is occupied.
        let cell = unsafe { A::slot_cell(key) };
        unsafe { (*(*cell).value).assume_init_mut() }
    }

    /// Removes and returns the value for the given key.
    ///
    /// # Safety
    ///
    /// The key must be valid and no references to this slot exist.
    pub unsafe fn remove_by_key(key: Key) -> A::Item {
        // SAFETY: Caller guarantees key validity.
        // Union field `value` is active because the slot is occupied.
        let cell = unsafe { A::slot_cell(key) };
        let value = unsafe { ptr::read((*cell).value.as_ptr()) };

        // SAFETY: Value moved out, key valid
        unsafe { A::dealloc(key) };

        value
    }

    /// Returns the raw slot cell pointer.
    ///
    /// Used by `RcSlot` to clone handles without going through the allocator.
    #[inline]
    pub(crate) fn as_ptr(&self) -> *mut SlotCell<A::Item> {
        self.slot_ptr
    }

    /// Constructs a `Slot` from a raw pointer.
    ///
    /// # Safety
    ///
    /// `ptr` must point to a valid, occupied slot cell within an allocator of type `A`.
    #[inline]
    pub(crate) unsafe fn from_ptr(ptr: *mut SlotCell<A::Item>) -> Self {
        Slot {
            slot_ptr: ptr,
            _marker: PhantomData,
        }
    }
}

// =============================================================================
// Trait Implementations
// =============================================================================

impl<A: Alloc> Deref for Slot<A> {
    type Target = A::Item;

    #[inline]
    fn deref(&self) -> &Self::Target {
        // SAFETY: Slot owns this slot cell, union field `value` is active
        unsafe { (*self.slot_ptr).value.assume_init_ref() }
    }
}

impl<A: Alloc> DerefMut for Slot<A> {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        // SAFETY: Slot owns this slot cell exclusively, union field `value` is active
        unsafe { (*(*self.slot_ptr).value).assume_init_mut() }
    }
}

impl<A: Alloc> AsRef<A::Item> for Slot<A> {
    #[inline]
    fn as_ref(&self) -> &A::Item {
        self
    }
}

impl<A: Alloc> AsMut<A::Item> for Slot<A> {
    #[inline]
    fn as_mut(&mut self) -> &mut A::Item {
        self
    }
}

// Note: Borrow<A::Item> and BorrowMut<A::Item> are intentionally not implemented.
// A blanket impl conflicts with core's `impl<T> Borrow<T> for T`, and macro-generated
// impls break when the allocated type is defined in a different crate (orphan rule).
// Use Deref/AsRef instead. See Slot's doc comment for details.

impl<A: Alloc> Drop for Slot<A> {
    #[inline]
    fn drop(&mut self) {
        // Drop the value in place
        // SAFETY: We own the slot, union field `value` is active
        unsafe {
            ptr::drop_in_place((*(*self.slot_ptr).value).as_mut_ptr());
        }

        // Return slot to freelist by pointer (no key round-trip)
        // SAFETY: Value dropped, slot_ptr valid
        unsafe { A::dealloc_ptr(self.slot_ptr) };
    }
}

impl<A: Alloc> std::fmt::Debug for Slot<A>
where
    A::Item: std::fmt::Debug,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Slot")
            .field("key", &self.key())
            .field("value", &**self)
            .finish()
    }
}

// =============================================================================
// LocalStatic
// =============================================================================

/// A `'static` reference to a thread-local slab-allocated value.
///
/// Returned by [`RcSlot::leak()`]. The reference is valid for the lifetime of
/// the program, but cannot be sent to other threads because the backing slab
/// is thread-local.
///
/// Once leaked, the slot is permanently occupied — there is no way to reclaim it.
#[repr(transparent)]
pub struct LocalStatic<T: 'static> {
    ptr: *const T,
    _marker: PhantomData<*const ()>, // !Send + !Sync
}

impl<T> LocalStatic<T> {
    /// Creates a new `LocalStatic` from a raw pointer.
    ///
    /// # Safety
    ///
    /// The pointer must point to a valid, permanently-leaked value in a
    /// thread-local slab.
    #[inline]
    unsafe fn new(ptr: *const T) -> Self {
        LocalStatic {
            ptr,
            _marker: PhantomData,
        }
    }

    /// Returns a raw pointer to the value.
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self.ptr
    }
}

impl<T> Deref for LocalStatic<T> {
    type Target = T;

    #[inline]
    fn deref(&self) -> &T {
        // SAFETY: ptr came from a leaked RcSlot, value is alive forever,
        // and we're on the same thread (enforced by !Send)
        unsafe { &*self.ptr }
    }
}

impl<T> AsRef<T> for LocalStatic<T> {
    #[inline]
    fn as_ref(&self) -> &T {
        self
    }
}

impl<T> Clone for LocalStatic<T> {
    #[inline]
    fn clone(&self) -> Self {
        *self
    }
}

impl<T> Copy for LocalStatic<T> {}

impl<T: fmt::Debug> fmt::Debug for LocalStatic<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("LocalStatic").field(&self.as_ref()).finish()
    }
}

// =============================================================================
// RcSlot
// =============================================================================

/// Reference-counted handle to a slab-allocated value.
///
/// `RcSlot` is a cloneable, RAII handle backed by the existing slab allocator.
/// Cloning bumps the strong count. Dropping decrements it; when the last strong
/// reference drops, the value is dropped. The slab slot is freed when both
/// strong and weak counts reach zero.
///
/// 8 bytes — same as `Slot`.
///
/// # Thread Safety
///
/// `RcSlot` is `!Send` and `!Sync` (same as `Slot`). All access must be from
/// the thread that created the allocator.
#[must_use = "dropping RcSlot decrements the strong count"]
pub struct RcSlot<A: Alloc<Item = RcInner<T>>, T: 'static> {
    inner: ManuallyDrop<Slot<A>>,
    _phantom: PhantomData<T>,
}

impl<T: 'static, A: Alloc<Item = RcInner<T>>> RcSlot<A, T> {
    /// Creates a new `RcSlot` containing the given value.
    ///
    /// # Panics
    ///
    /// Panics with "out of memory" if the allocator is full (bounded only).
    #[inline]
    pub fn new(value: T) -> Self {
        RcSlot {
            inner: ManuallyDrop::new(Slot::new(RcInner::new(value))),
            _phantom: PhantomData,
        }
    }

    /// Tries to create a new `RcSlot` containing the given value.
    ///
    /// Returns `Err(Full(value))` if the allocator is at capacity.
    #[inline]
    pub fn try_new(value: T) -> Result<Self, Full<T>> {
        match Slot::try_new(RcInner::new(value)) {
            Ok(slot) => Ok(RcSlot {
                inner: ManuallyDrop::new(slot),
                _phantom: PhantomData,
            }),
            Err(full) => Err(Full(full.into_inner().into_value())),
        }
    }

    /// Creates a weak reference to the same slab slot.
    #[inline]
    pub fn downgrade(&self) -> WeakSlot<A, T> {
        let rc_inner: &RcInner<T> = &self.inner;
        rc_inner.set_weak(rc_inner.weak() + 1);
        // SAFETY: We hold a strong ref, slot is alive. Duplicate the pointer.
        let weak_slot = unsafe { Slot::from_ptr(self.inner.as_ptr()) };
        WeakSlot {
            inner: ManuallyDrop::new(weak_slot),
            _phantom: PhantomData,
        }
    }

    /// Leaks the `RcSlot`, returning a permanent reference to the value.
    ///
    /// The strong count is NOT decremented. The slot will never be freed.
    /// This is useful for values that must live for the entire program.
    #[inline]
    pub fn leak(self) -> LocalStatic<T> {
        // Get pointer to T through Deref chain: self -> &RcInner<T> -> &T
        let rc_inner: &RcInner<T> = &self.inner;
        let ptr: *const T = rc_inner.value();
        std::mem::forget(self);
        // SAFETY: We just forgot self, so the value lives forever.
        // The pointer is valid and the slot won't be deallocated.
        unsafe { LocalStatic::new(ptr) }
    }

    /// Returns the strong reference count.
    #[inline]
    pub fn strong_count(&self) -> u32 {
        let rc_inner: &RcInner<T> = &self.inner;
        rc_inner.strong()
    }

    /// Returns the weak reference count (excludes the implicit weak).
    #[inline]
    pub fn weak_count(&self) -> u32 {
        let rc_inner: &RcInner<T> = &self.inner;
        rc_inner.weak() - 1
    }

    /// Returns a mutable reference if this is the only reference.
    ///
    /// Returns `None` if there are other strong or weak references.
    #[inline]
    pub fn get_mut(&mut self) -> Option<&mut T> {
        // Need strong == 1 AND weak == 0 (no outstanding weaks that could upgrade)
        if self.strong_count() == 1 && self.weak_count() == 0 {
            // SAFETY: We verified exclusive access
            Some(unsafe { self.get_mut_unchecked() })
        } else {
            None
        }
    }

    /// Returns a mutable reference to the value without checking the strong count.
    ///
    /// # Safety
    ///
    /// Caller must ensure this is the only `RcSlot` (strong_count == 1, weak_count == 0)
    /// and no `WeakSlot::upgrade` calls are concurrent.
    #[inline]
    #[allow(clippy::mut_from_ref)]
    pub unsafe fn get_mut_unchecked(&self) -> &mut T {
        // SAFETY: Caller guarantees exclusive access.
        // Navigate through SlotCell union → RcInner → ManuallyDrop<T> → T
        let cell_ptr = self.inner.as_ptr();
        let rc_inner = unsafe { (*(*cell_ptr).value).assume_init_mut() };
        // SAFETY: value is live, caller guarantees exclusive access.
        // Dereference through ManuallyDrop to get &mut T.
        let md = unsafe { rc_inner.value_manual_drop_mut() };
        &mut *md
    }
}

impl<T: 'static + Clone, A: Alloc<Item = RcInner<T>>> RcSlot<A, T> {
    /// Makes a mutable reference to the value, cloning if necessary.
    ///
    /// If this is the only reference (strong == 1, weak == 0), returns a
    /// mutable reference directly. Otherwise, clones the value into a new
    /// slot and returns a mutable reference to the clone.
    ///
    /// # Panics
    ///
    /// Panics if allocation fails (bounded allocator at capacity).
    #[inline]
    pub fn make_mut(&mut self) -> &mut T {
        if self.strong_count() != 1 || self.weak_count() != 0 {
            // Clone into new slot, replace self
            *self = Self::new((**self).clone());
        }
        // SAFETY: Now we're the only reference
        unsafe { self.get_mut_unchecked() }
    }
}

impl<T: 'static, A: Alloc<Item = RcInner<T>>> Clone for RcSlot<A, T> {
    #[inline]
    fn clone(&self) -> Self {
        let rc_inner: &RcInner<T> = &self.inner;
        rc_inner.set_strong(rc_inner.strong() + 1);
        // SAFETY: We hold a strong ref, slot is alive
        let cloned_slot = unsafe { Slot::from_ptr(self.inner.as_ptr()) };
        RcSlot {
            inner: ManuallyDrop::new(cloned_slot),
            _phantom: PhantomData,
        }
    }
}

impl<T: 'static, A: Alloc<Item = RcInner<T>>> Drop for RcSlot<A, T> {
    #[inline]
    fn drop(&mut self) {
        // All refcount access goes through raw pointers to avoid Stacked
        // Borrows invalidation when we take &mut to drop the value.
        let cell_ptr = self.inner.as_ptr();

        // SAFETY: Slot is alive, union field `value` is active
        let strong = unsafe { (*cell_ptr).value.assume_init_ref().strong() };
        if strong > 1 {
            // SAFETY: same as above
            unsafe { (*cell_ptr).value.assume_init_ref().set_strong(strong - 1) };
            return;
        }

        // Last strong reference — drop the value
        // SAFETY: same as above
        unsafe { (*cell_ptr).value.assume_init_ref().set_strong(0) };

        // SAFETY: We are the last strong ref, value is live. We need &mut
        // to drop the ManuallyDrop<T> inside RcInner.
        unsafe {
            let rc_inner_mut = (*(*cell_ptr).value).assume_init_mut();
            ManuallyDrop::drop(rc_inner_mut.value_manual_drop_mut());
        }

        // Re-derive shared ref after the mutable drop above
        // SAFETY: RcInner is still valid memory (Cell<u32> fields are Copy,
        // ManuallyDrop<T> is dropped but the storage is still there)
        let weak = unsafe { (*cell_ptr).value.assume_init_ref().weak() };
        if weak == 1 {
            // No outstanding weaks — dealloc the slot.
            // SAFETY: Value is dropped. Slot's drop_in_place on RcInner is
            // a no-op (ManuallyDrop<T> already dropped, Cell<u32> is Copy).
            // Slot's Drop will call dealloc_ptr to return slot to freelist.
            unsafe { ManuallyDrop::drop(&mut self.inner) };
        } else {
            // SAFETY: same as weak read above
            unsafe { (*cell_ptr).value.assume_init_ref().set_weak(weak - 1) };
            // Zombie: T dropped, weak refs still hold the slot alive
        }
    }
}

impl<T: 'static, A: Alloc<Item = RcInner<T>>> Deref for RcSlot<A, T> {
    type Target = T;

    #[inline]
    fn deref(&self) -> &T {
        let rc_inner: &RcInner<T> = &self.inner;
        rc_inner.value()
    }
}

impl<T: 'static, A: Alloc<Item = RcInner<T>>> AsRef<T> for RcSlot<A, T> {
    #[inline]
    fn as_ref(&self) -> &T {
        self
    }
}

impl<T: 'static + fmt::Debug, A: Alloc<Item = RcInner<T>>> fmt::Debug for RcSlot<A, T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("RcSlot")
            .field("strong", &self.strong_count())
            .field("weak", &self.weak_count())
            .field("value", &**self)
            .finish()
    }
}

// =============================================================================
// WeakSlot
// =============================================================================

/// Weak reference to a slab-allocated value.
///
/// Does not keep the value alive. Must [`upgrade`](Self::upgrade) to access
/// the value. Keeps the slab slot alive (for upgrade checks) until all weak
/// and strong references are dropped.
///
/// 8 bytes — same as `Slot`.
pub struct WeakSlot<A: Alloc<Item = RcInner<T>>, T: 'static> {
    inner: ManuallyDrop<Slot<A>>,
    _phantom: PhantomData<T>,
}

impl<T: 'static, A: Alloc<Item = RcInner<T>>> WeakSlot<A, T> {
    /// Attempts to upgrade to a strong reference.
    ///
    /// Returns `Some(RcSlot)` if the value is still alive (strong > 0),
    /// or `None` if the last strong reference has been dropped.
    #[inline]
    pub fn upgrade(&self) -> Option<RcSlot<A, T>> {
        let rc_inner: &RcInner<T> = &self.inner;
        let strong = rc_inner.strong();
        if strong == 0 {
            return None;
        }
        rc_inner.set_strong(strong + 1);
        // SAFETY: strong > 0 means slot is alive and value is valid
        let slot = unsafe { Slot::from_ptr(self.inner.as_ptr()) };
        Some(RcSlot {
            inner: ManuallyDrop::new(slot),
            _phantom: PhantomData,
        })
    }

    /// Returns the strong reference count.
    #[inline]
    pub fn strong_count(&self) -> u32 {
        let rc_inner: &RcInner<T> = &self.inner;
        rc_inner.strong()
    }

    /// Returns the weak reference count (excludes the implicit weak).
    #[inline]
    pub fn weak_count(&self) -> u32 {
        let rc_inner: &RcInner<T> = &self.inner;
        let weak = rc_inner.weak();
        // If strong > 0, subtract the implicit weak. If strong == 0,
        // the implicit weak was already decremented.
        if rc_inner.strong() > 0 {
            weak - 1
        } else {
            weak
        }
    }
}

impl<T: 'static, A: Alloc<Item = RcInner<T>>> Clone for WeakSlot<A, T> {
    #[inline]
    fn clone(&self) -> Self {
        let rc_inner: &RcInner<T> = &self.inner;
        rc_inner.set_weak(rc_inner.weak() + 1);
        // SAFETY: We hold a weak ref, slot memory is alive
        let cloned_slot = unsafe { Slot::from_ptr(self.inner.as_ptr()) };
        WeakSlot {
            inner: ManuallyDrop::new(cloned_slot),
            _phantom: PhantomData,
        }
    }
}

impl<T: 'static, A: Alloc<Item = RcInner<T>>> Drop for WeakSlot<A, T> {
    #[inline]
    fn drop(&mut self) {
        let rc_inner: &RcInner<T> = &self.inner;
        let weak = rc_inner.weak();
        if weak > 1 {
            rc_inner.set_weak(weak - 1);
            return;
        }
        // Last weak reference (weak == 1)
        if rc_inner.strong() == 0 {
            // Zombie slot — value already dropped, dealloc the slot.
            // SAFETY: RcInner's ManuallyDrop<T> is already dropped.
            // Slot's drop_in_place on RcInner is a no-op. Dealloc returns
            // the slot to the freelist.
            unsafe { ManuallyDrop::drop(&mut self.inner) };
        }
        // If strong > 0, this shouldn't happen (strong holder holds implicit weak).
        // But if it does, the strong holder's drop will handle dealloc.
    }
}

impl<T: 'static, A: Alloc<Item = RcInner<T>>> fmt::Debug for WeakSlot<A, T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("WeakSlot")
            .field("strong", &self.strong_count())
            .field("weak", &self.weak_count())
            .finish()
    }
}
