//! Generic slab allocator trait and slot type.
//!
//! This module provides:
//! - [`Alloc`] - trait for ZST allocators generated by macros
//! - [`Slot`] - 8-byte RAII handle generic over allocator
//! - [`BoundedAlloc`] / [`UnboundedAlloc`] - marker traits

use std::fmt;
use std::marker::PhantomData;
use std::ops::{Deref, DerefMut};

use crate::Key;
use crate::shared::SlotCell;

// =============================================================================
// Full<T>
// =============================================================================

/// Error returned when a bounded allocator is full.
///
/// Contains the value that could not be allocated, allowing recovery.
pub struct Full<T>(pub T);

impl<T> Full<T> {
    /// Consumes the error, returning the value that could not be allocated.
    #[inline]
    pub fn into_inner(self) -> T {
        self.0
    }
}

impl<T> fmt::Debug for Full<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("Full(..)")
    }
}

impl<T> fmt::Display for Full<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("allocator full")
    }
}

// =============================================================================
// Traits
// =============================================================================

/// Trait for zero-sized slab allocators backed by thread-local storage.
///
/// Each macro-generated allocator is a ZST that implements this trait.
/// All operations go through associated functions (no `&self`) since
/// the backing storage lives in a `thread_local!`.
///
/// # Safety
///
/// Implementors must guarantee:
/// - `try_alloc` returns a valid, claimed slot pointer with value written
/// - `dealloc` correctly returns the slot to the freelist (by key)
/// - `dealloc_ptr` correctly returns the slot to the freelist (by pointer)
/// - `slot_cell` returns a valid pointer for any key returned by `try_alloc`
/// - All operations are single-threaded (TLS-backed)
pub unsafe trait Alloc: Sized + 'static {
    /// The type stored in each slot.
    type Item: 'static;

    /// Claim a slot, write the value, and mark it occupied.
    ///
    /// Returns `Err(Full(value))` if the allocator is full, giving the
    /// value back to the caller.
    fn try_alloc(value: Self::Item) -> Result<*mut SlotCell<Self::Item>, Full<Self::Item>>;

    /// Claim a slot, write the value, and mark it occupied.
    ///
    /// # Panics
    ///
    /// Panics with "out of memory" if the allocator is full.
    fn alloc(value: Self::Item) -> *mut SlotCell<Self::Item> {
        Self::try_alloc(value).expect("out of memory")
    }

    /// Return a slot to the freelist by key (cold path).
    ///
    /// # Safety
    ///
    /// - `key` must refer to a previously allocated, occupied slot
    /// - The value must already be dropped or moved out
    unsafe fn dealloc(key: Key);

    /// Return a slot to the freelist by pointer (hot path).
    ///
    /// This avoids the key→pointer round-trip that `dealloc` requires.
    ///
    /// # Safety
    ///
    /// - `slot_ptr` must point to a previously allocated, occupied slot
    /// - The value must already be dropped or moved out
    unsafe fn dealloc_ptr(slot_ptr: *mut SlotCell<Self::Item>);

    /// Get the slot cell pointer for a key.
    ///
    /// # Safety
    ///
    /// `key` must refer to a valid slot within the slab.
    unsafe fn slot_cell(key: Key) -> *mut SlotCell<Self::Item>;

    /// Compute the key for a slot pointer (cold path).
    ///
    /// This is the inverse of `slot_cell`: given a pointer, compute the key.
    /// Used for lazy key computation in `Slot::key()`.
    fn slot_index(slot_ptr: *mut SlotCell<Self::Item>) -> Key;

    /// Check if a key refers to an occupied slot.
    fn contains_key(key: Key) -> bool;
}

/// Marker trait for bounded (fixed-capacity) allocators.
pub trait BoundedAlloc: Alloc {}

/// Marker trait for unbounded (growable) allocators.
pub trait UnboundedAlloc: Alloc {}

// =============================================================================
// Slot<A>
// =============================================================================

/// RAII handle to a slab-allocated value, generic over allocator.
///
/// `Slot<A>` is 8 bytes (one pointer). The key is computed lazily from the
/// pointer when needed.
///
/// This is the slot type generated by `bounded_allocator!` and
/// `unbounded_allocator!` macros via `type Slot = alloc::Slot<Allocator>`.
///
/// # Thread Safety
///
/// `Slot` is `!Send` and `!Sync` (via `PhantomData<*const ()>` inside the
/// marker). It must only be used from the thread that created it.
#[must_use = "dropping Slot returns it to the allocator"]
pub struct Slot<A: Alloc> {
    slot_ptr: *mut SlotCell<A::Item>,
    // PhantomData carries the allocator type AND makes Slot !Send + !Sync
    // (*mut is !Send + !Sync, and PhantomData<A> ties the type)
    _marker: PhantomData<(A, *const ())>,
}

impl<A: Alloc> Slot<A> {
    /// Creates a new slot containing the given value.
    ///
    /// # Panics
    ///
    /// Panics with "out of memory" if the allocator is full (bounded only).
    #[inline]
    pub fn new(value: A::Item) -> Self {
        Slot {
            slot_ptr: A::alloc(value),
            _marker: PhantomData,
        }
    }

    /// Tries to create a new slot containing the given value.
    ///
    /// Returns `Err(Full(value))` if the allocator is at capacity,
    /// giving the value back to the caller.
    #[inline]
    pub fn try_new(value: A::Item) -> Result<Self, Full<A::Item>> {
        let slot_ptr = A::try_alloc(value)?;
        Ok(Slot {
            slot_ptr,
            _marker: PhantomData,
        })
    }

    /// Returns the key for this slot.
    ///
    /// Lazily computed from pointer offset. This is a cold-path operation.
    #[inline]
    pub fn key(&self) -> Key {
        A::slot_index(self.slot_ptr)
    }

    /// Leaks the slot, returning its key for later access.
    ///
    /// The slot is NOT deallocated. Use key-based methods to access
    /// or eventually remove it.
    #[inline]
    pub fn leak(self) -> Key {
        let key = self.key();
        std::mem::forget(self);
        key
    }

    /// Extracts the value from the slot, deallocating the slot.
    ///
    /// This is analogous to `Box::into_inner`.
    pub fn into_inner(self) -> A::Item {
        // SAFETY: We own the slot, value is valid
        let value = unsafe {
            let slot = &*self.slot_ptr;
            std::ptr::read(slot.value_ptr())
        };

        // SAFETY: Value has been moved out, slot_ptr is valid
        unsafe { A::dealloc_ptr(self.slot_ptr) };

        std::mem::forget(self);
        value
    }

    /// Replaces the value in the slot, returning the old value.
    #[inline]
    pub fn replace(&mut self, value: A::Item) -> A::Item {
        // SAFETY: We own the slot exclusively (&mut self)
        unsafe {
            let slot = &*self.slot_ptr;
            let ptr = slot.value_ptr_mut();
            let old = std::ptr::read(ptr);
            std::ptr::write(ptr, value);
            old
        }
    }

    /// Checks if a key refers to a valid, occupied slot.
    #[inline]
    pub fn contains_key(key: Key) -> bool {
        A::contains_key(key)
    }

    /// Returns a reference to the value for the given key.
    ///
    /// # Safety
    ///
    /// The key must be valid (from `leak()` or `key()`, not yet removed).
    #[inline]
    pub unsafe fn from_key(key: Key) -> &'static A::Item {
        // SAFETY: Caller guarantees key validity. TLS storage is 'static.
        let cell = unsafe { A::slot_cell(key) };
        unsafe { (*cell).get_value() }
    }

    /// Returns a mutable reference to the value for the given key.
    ///
    /// # Safety
    ///
    /// The key must be valid and no other references to this slot exist.
    #[inline]
    pub unsafe fn from_key_mut(key: Key) -> &'static mut A::Item {
        // SAFETY: Caller guarantees key validity and exclusivity.
        let cell = unsafe { A::slot_cell(key) };
        unsafe { (*cell).get_value_mut() }
    }

    /// Removes and returns the value for the given key.
    ///
    /// # Safety
    ///
    /// The key must be valid and no references to this slot exist.
    pub unsafe fn remove_by_key(key: Key) -> A::Item {
        // SAFETY: Caller guarantees key validity
        let cell = unsafe { A::slot_cell(key) };
        let value = unsafe { std::ptr::read((*cell).value_ptr()) };

        // SAFETY: Value moved out, key valid
        unsafe { A::dealloc(key) };

        value
    }
}

// =============================================================================
// Trait Implementations
// =============================================================================

impl<A: Alloc> Deref for Slot<A> {
    type Target = A::Item;

    #[inline]
    fn deref(&self) -> &Self::Target {
        // SAFETY: Slot owns this slot cell, value is initialized
        unsafe { (*self.slot_ptr).get_value() }
    }
}

impl<A: Alloc> DerefMut for Slot<A> {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        // SAFETY: Slot owns this slot cell exclusively, value is initialized
        unsafe { (*self.slot_ptr).get_value_mut() }
    }
}

impl<A: Alloc> AsRef<A::Item> for Slot<A> {
    #[inline]
    fn as_ref(&self) -> &A::Item {
        self
    }
}

impl<A: Alloc> AsMut<A::Item> for Slot<A> {
    #[inline]
    fn as_mut(&mut self) -> &mut A::Item {
        self
    }
}

// Note: Borrow<A::Item> and BorrowMut<A::Item> cannot be implemented generically
// due to the blanket `impl<T> Borrow<T> for T` in core. The macros generate these
// impls where the concrete type is known.

impl<A: Alloc> Drop for Slot<A> {
    fn drop(&mut self) {
        // Drop the value in place
        // SAFETY: We own the slot, value is initialized
        unsafe {
            std::ptr::drop_in_place((*self.slot_ptr).value_ptr_mut());
        }

        // Return slot to freelist by pointer (no key round-trip)
        // SAFETY: Value dropped, slot_ptr valid
        unsafe { A::dealloc_ptr(self.slot_ptr) };
    }
}

impl<A: Alloc> std::fmt::Debug for Slot<A>
where
    A::Item: std::fmt::Debug,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Slot")
            .field("key", &self.key())
            .field("value", &**self)
            .finish()
    }
}
